name: Run YouTube Live Link Script

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours, adjust as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      - name: Run Youtube Live Link script
        run: python Youtube_Live_Link.py

      - name: Commit and push changes if updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add YT_playlist.m3u
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            current_time=$(date +"%Y-%m-%d %H:%M:%S")
            git commit -m "Updated m3u playlist via Action every 3 hours at $current_time"
            git push
          fi
