name: YouTube Live Link Check

on:
  schedule:
    - cron: '10 */3 * * *'  # Runs every 3 hours at minute 10
  workflow_dispatch:        # Allows manual run

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir yt_dlp google-api-python-client

      - name: Run script
        run: python main.py

      - name: Commit and push changes if updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if ! git diff --quiet YT_playlist.m3u; then
            git add YT_playlist.m3u
            git commit -m "Updated m3u playlist via Action at $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
