name: YouTube Live Link Check

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 30 minutes past the hour, every 3 hours, between 07:00 and 23:59.
  workflow_dispatch: # Allows you to run the workflow manually from the GitHub interface

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client requests beautifulsoup4
    
    - name: Load all secrects
      env:
        COOKIES: ${{ secrets.COOKIES }}  # Load secret into env variable
      run: |
        echo "$COOKIES" > cookies.txt
        # Quick validation
        file cookies.txt

    - name: Run script
      env:
        YOUTUBE_API_1: ${{ secrets.YOUTUBE_API_1 }}
        YOUTUBE_API_2: ${{ secrets.YOUTUBE_API_2 }}
        YOUTUBE_API_3: ${{ secrets.YOUTUBE_API_3 }}
        YOUTUBE_API_4: ${{ secrets.YOUTUBE_API_4 }}
        YOUTUBE_API_5: ${{ secrets.YOUTUBE_API_5 }}
        YOUTUBE_API_6: ${{ secrets.YOUTUBE_API_6 }}
        YOUTUBE_API_7: ${{ secrets.YOUTUBE_API_7 }}
        YOUTUBE_API_8: ${{ secrets.YOUTUBE_API_8 }}
        YOUTUBE_API_9: ${{ secrets.YOUTUBE_API_9 }}
      run: |
        python main.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add youtube_page.html
        git commit -m 'Updated m3u playlist via Action in every 3 Hours'
        git push
