name: YouTube Live Link Check

on:
  schedule:
    # Runs every 4 hours at minute 10 (08:10, 12:10, 16:10, 20:10 UTC+6)
    - cron: '10 */4 * * *'
  workflow_dispatch:      # Allows manual run

jobs:
  gathering_all_IPTV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create cookies.txt from secret
      run: |
        echo "${{ secrets.COOKIES }}" > cookies.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt_dlp 

    - name: Setup fast static FFmpeg
      run: |
        wget -q https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-master-latest-linux64-gpl.tar.xz -O ffmpeg.tar.xz
        tar -xf ffmpeg.tar.xz
        FFMPEG_DIR=$(ls -d ffmpeg-master-*)
        sudo cp "$FFMPEG_DIR/bin/ffmpeg" /usr/local/bin/
        sudo cp "$FFMPEG_DIR/bin/ffprobe" /usr/local/bin/
        ffmpeg -version

    - name: Run main script to get all latest links from YouTube
      run: |
        python main.py

    - name: Commit and push YouTube playlist (YT_playlist.m3u)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        git add YT_playlist.m3u
        if git diff --cached --quiet; then
            echo "No changes to YT_playlist.m3u"
        else
            git commit -m "Update YouTube playlist ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push
        fi

    - name: Run combine_playlist script to combine YouTube and Working_playlist together
      run: |
        python combine_playlists.py

    - name: Commit and push combined playlist (combined.m3u)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add combined.m3u
        if git diff --cached --quiet; then
            echo "No changes to combined.m3u"
        else
            git commit -m "Update combined playlist ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push
        fi



