name: YouTube Live Link Check

on:
  schedule:
  # UTC times equivalent to 08:10, 12:10, 16:10, 20:10 in Bangladesh (UTC+6)
    - cron: '10 */4 * * *'
  workflow_dispatch:      # Allows manual run

jobs:
  gathering_all_IPTV:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt_dlp google-api-python-client

    - name: Setup fast static FFmpeg
      run: |
        wget -q https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -O ffmpeg.tar.xz
        tar -xf ffmpeg.tar.xz
        FFMPEG_DIR=$(ls -d ffmpeg-*amd64-static)
        sudo cp "$FFMPEG_DIR/ffmpeg" /usr/local/bin/
        sudo cp "$FFMPEG_DIR/ffprobe" /usr/local/bin/
        ffmpeg -version

    - name: Run main script to get all latest link from YouTube
      run: |
        python main.py

    - name: Commit and push changes if updated(YT_playlist.m3u)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add YT_playlist.m3u
        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Updated m3u playlist via Action every 3 hours at $current_time"
          git push
        fi

    - name: Combine YouTube and Working_playlist together
      run: python combine_playlists.py

    - name: Commit and push combined playlist(combined.m3u)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add combined.m3u
        if git diff --cached --quiet; then
          echo "No combined.m3u changes to commit"
        else
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          git commit -m "Updated combined.m3u at $current_time"
          git push
        fi


