name: YouTube Fetch

on:
  schedule:
    - cron: '30 7-23/3 * * *' # Runs at 30 minutes past the hour, every 3 hours, between 07:00 and 23:59.
  workflow_dispatch: # Allows you to run the workflow manually from the GitHub interface

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client requests beautifulsoup4

    - name: Run script
      env:
        API_KEY: ${{ secrets.YOUTUBE_API_KEY }} # Store your API keys as secrets in the GitHub repository
      run: |
        python main.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add YT_playlist.m3u
        git commit -m 'Updated m3u playlist'
        git push
